#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-japicmp
Version  : 0.10.0
Release  : 2
URL      : https://github.com/siom79/japicmp/archive/japicmp-base-0.10.0.tar.gz
Source0  : https://github.com/siom79/japicmp/archive/japicmp-base-0.10.0.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/com/github/siom79/japicmp/japicmp-base/0.10.0/japicmp-base-0.10.0.pom
Source2  : https://repo.gradle.org/gradle/libs-releases/com/github/siom79/japicmp/japicmp/0.10.0/japicmp-0.10.0.jar
Source3  : https://repo.gradle.org/gradle/libs-releases/com/github/siom79/japicmp/japicmp/0.10.0/japicmp-0.10.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-japicmp-data = %{version}-%{release}
Requires: mvn-japicmp-license = %{version}-%{release}

%description
The website is located at [https://siom79.github.io/japicmp](https://siom79.github.io/japicmp/).

%package data
Summary: data components for the mvn-japicmp package.
Group: Data

%description data
data components for the mvn-japicmp package.


%package license
Summary: license components for the mvn-japicmp package.
Group: Default

%description license
license components for the mvn-japicmp package.


%prep
%setup -q -n japicmp-japicmp-base-0.10.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-japicmp
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-japicmp/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp-base/0.10.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp-base/0.10.0/japicmp-base-0.10.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp/0.10.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp/0.10.0/japicmp-0.10.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp/0.10.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp/0.10.0/japicmp-0.10.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp-base/0.10.0/japicmp-base-0.10.0.pom
/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp/0.10.0/japicmp-0.10.0.jar
/usr/share/java/.m2/repository/com/github/siom79/japicmp/japicmp/0.10.0/japicmp-0.10.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-japicmp/LICENSE
